name: skill_up
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2   # stabile e diffusa con Dart 3.x
  flutter_secure_storage: ^9.2.1
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  # ðŸ‘ˆ aggiunto

flutter:
  uses-material-design: true

  assets:
    - assets/brand/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/brand/skillup_logo.png"
  adaptive_icon_background: "#FFFFFF"  # colore di sfondo (puoi cambiarlo)
  adaptive_icon_foreground: "assets/brand/skillup_logo.png"
